-- One review table per investigation: the full flagged record + the 4 audit fields (+ who/when).
-- case_key = the key columns joined with '|' (see lib/investigations.ts keyCols); the matching view hides
-- any case present here. The app adds new view columns here automatically (ALTER TABLE ADD COLUMN).
-- Safe to re-run: IF NOT EXISTS never touches existing data.

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_1_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_id_text STRING,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_2_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_id_text STRING,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  diff_min_ticket_created_vs_02_pending_approval INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_2_1_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  diff_min_ticket_created_vs_02_pending_approval INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_3_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  diff_min_ticket_created_vs_02_pending_approval INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_4_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  diff_min_ticket_created_vs_02_pending_approval INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_1_41_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_id_text STRING,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  diff_min_ticket_created_vs_02_pending_approval INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_2_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  diff_min_1st_connect_vs_10_order_approved INT64,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_3_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_6_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_7_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  current_order_status STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_9_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  customer_name STRING,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  order_phone_number_1 STRING,
  lead_phone_number STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_10_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  first_connect_time_true_false BOOL,
  lead_sources STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_11_reviews` (
  case_key STRING,
  purchase_date DATE,
  oldest_order_number STRING,
  customer_name STRING,
  amount FLOAT64,
  newest_order_number STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_14_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  current_order_status STRING,
  lead_created_at DATE,
  final_assigned_to_name STRING,
  helper_budget INT64,
  assigned_team_acc_to_budget STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_15_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  current_order_status STRING,
  lead_created_at DATE,
  final_assigned_to_name STRING,
  helper_budget INT64,
  assigned_team_acc_to_budget STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `mis-gempundit.order_verification.inv_16_reviews` (
  case_key STRING,
  approval_timestamp DATETIME,
  sales_person STRING,
  oldest_order_number STRING,
  order_date_time TIMESTAMP,
  total_amount FLOAT64,
  newest_order_no STRING,
  tickets_id STRING,
  ticket_created_at DATETIME,
  first_connected_time DATETIME,
  mtd_form_filled_timestamp DATETIME,
  username_frontend STRING,
  lead_sources STRING,
  payment_method STRING,
  order_type_in_mtd_form STRING,
  pending_approval_02_step_timestamp DATETIME,
  current_order_status STRING,
  lead_created_at DATE,
  final_assigned_to_name STRING,
  auditor STRING,
  decision_types STRING,
  decided_sales_person STRING,
  comments STRING,
  created_by STRING,
  created_at TIMESTAMP,
  updated_by STRING,
  updated_at TIMESTAMP
);
